"""Add review_status to Subscription

Revision ID: 1ed7835594ae
Revises: 5fff85ca1a9a
Create Date: 2025-04-25 15:56:10.273571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed7835594ae'
down_revision: Union[str, None] = '5fff85ca1a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('review_status', sa.String(), nullable=False, server_default='PENDING'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'review_status')
    # ### end Alembic commands ###
