"""add scanned_mails received_at column

Revision ID: 2416cbc4687a
Revises: 1ed7835594ae
Create Date: 2025-06-11 20:51:04.753141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2416cbc4687a'
down_revision: Union[str, None] = '1ed7835594ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanned_mails', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.alter_column('subscriptions', 'review_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'review_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_column('scanned_mails', 'received_at')
    # ### end Alembic commands ###
