"""add received_at and improve scanned_mail

Revision ID: add746daeb0c
Revises: 2416cbc4687a
Create Date: 2025-06-11 21:43:27.485719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add746daeb0c'
down_revision: Union[str, None] = '2416cbc4687a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'scanned_mails', 'subscriptions', ['external_id'], ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scanned_mails', type_='foreignkey')
    # ### end Alembic commands ###

def upgrade() -> None:
    op.add_column('scanned_mails', sa.Column('received_at', sa.DateTime(), nullable=True))
