"""Add review_status

Revision ID: ee878e9568e1
Revises: 76fc01517b27
Create Date: 2025-04-20 16:43:50.595258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee878e9568e1'
down_revision: Union[str, None] = '76fc01517b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('review_status', sa.String(), nullable=True))
    op.drop_column('subscriptions', 'approved')
    op.drop_column('subscriptions', 'reviewed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('reviewed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'review_status')
    # ### end Alembic commands ###
