"""Add rejection_reason to Subscription

Revision ID: f4d35eaef1eb
Revises: ee878e9568e1
Create Date: 2025-04-22 14:05:41.996954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d35eaef1eb'
down_revision: Union[str, None] = 'ee878e9568e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.drop_column('subscriptions', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'rejection_reason')
    # ### end Alembic commands ###
